# Generated by Django 3.1.3 on 2020-11-08 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='Task',
            new_name='Work',
        ),
    ]
